/* The extern module `hashes` of hash_c.lcd, in C. hashes.h is generated by
   `lcd c` beside the program: the prototypes and the typedefs of the
   record (hashes_pair) and the vectors (lucid_arr_uint32_3, _2); a Lite bool
   is a uint8_t there, 0 or 1. */
#include "hashes.h"

static uint32_t noted[64];
static int nnoted;

uint32_t hashes_mix(uint32_t x, uint32_t y) { return (x * 31u) ^ y; }

hashes_pair hashes_swap(hashes_pair p) { hashes_pair q = { p.b, p.a }; return q; }

uint32_t hashes_sum(lucid_arr_uint32_3 xs) { return xs._0 + xs._1 + xs._2; }

lucid_arr_uint32_2 hashes_halves(uint64_t v) { lucid_arr_uint32_2 h = { (uint32_t)(v >> 32), (uint32_t)v }; return h; }

uint8_t hashes_seen(uint32_t x) {
  for (int i = 0; i < nnoted; i++) if (noted[i] == x) return true;
  if (nnoted < 64) noted[nnoted++] = x;
  return false;
}
